## Python Assignment 2 : Data Structures, Functions, Numpy & Pandas

### Section A: Data Structures & Control Structures

#### 1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [1]:
list = [1,2,3,4,5]
print(list)

[1, 2, 3, 4, 5]

In [2]:
# append
list.append(6) # add element in last position
list

[1, 2, 3, 4, 5, 6]

In [3]:
# extend
list.extend([1,2,3])  # merge the list
list

[1, 2, 3, 4, 5, 6, 1, 2, 3]

In [4]:
# insert
list.insert(6,7)  # (index, value)
list

[1, 2, 3, 4, 5, 6, 7, 1, 2, 3]

In [37]:
# remove
list.remove(7) # remove first match value
list

ValueError: list.remove(x): x not in list

In [ ]:
# pop
list.pop(6)  # pop index placed value
list

In [7]:
#index
list.index(5) # show the index of 5

4

In [8]:
# count
list.count(3)  # Counts how many times a value appears.

2

In [9]:
# sort
list.sort()  # sort the list into ascending order.
list

[1, 2, 2, 3, 3, 4, 5, 6]

In [10]:
# reverse
list.reverse()   # reverse the list
list

[6, 5, 4, 3, 3, 2, 2, 1]

In [11]:
# sort
list.sort(reverse = True)  # sort the list into descending order.
list

[6, 5, 4, 3, 3, 2, 2, 1]

In [12]:
# clear
list.clear()   # delete all the elements in list
list

[]

#### 2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why

In [13]:
student_list = ['tim', 'jim', 'tom']
student_list[1] = 'jack'
print(student_list)

['tim', 'jack', 'tom']

tuple is immutable
we can't change tuples data like list

list is mutable
we can make changes

#### 3. Create a set of integers with some duplicate values. Print the set and explain the output.

In [14]:
s = {1,2,4,3,4,5,6,3,7}
s

{1, 2, 3, 4, 5, 6, 7}

sets automatically remove duplicate values
Even if you write duplicates, the set keeps only one copy

#### 4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [15]:
dict = {
    'name' : 'tom',
    'age'  : 20,
    'city' : 'bengaluru'
}
dict

{'name': 'tom', 'age': 20, 'city': 'bengaluru'}

In [16]:
#update age
dict['age'] = 21
dict

{'name': 'tom', 'age': 21, 'city': 'bengaluru'}

In [17]:
# adding new key
dict['email'] = 'tom123@gmail.com'
dict

{'name': 'tom', 'age': 21, 'city': 'bengaluru', 'email': 'tom123@gmail.com'}

In [18]:
for key , value in  dict.items():
    print(key, ':', value)

name : tom
age : 21
city : bengaluru
email : tom123@gmail.com

#### 5.  Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [19]:
# age = 21
age = int(input("enter the age : "))

if age >= 18:
    print("you are eligible to vote")
else:
    print("you are not eligible to vote")

enter the age :  22

you are eligible to vote

#### 6. Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [20]:
mark = int(input("enter your marks : "))

if mark >=90:
    print("grade: A")
elif mark >= 75:
    print("grade: B")
elif mark >= 50:
    print("grade: C")
else:
    print("Fail")

enter your marks :  93

grade: A

#### 7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [21]:
num = int(input("Enter number : "))

if num > 0:
    print(num)
    print("The number is positive")

    if  num%2 == 0:
        print("The number is also even")

elif num == 0:
    print ("the number is zero")

else:
    print("the number is negative")

Enter number :  3

3
The number is positive

### Section B: Numpy

#### 8. Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [22]:
import numpy as np

In [23]:
# 0D
scalar = np.array(5)
scalar

array(5)

In [24]:
# 1D
d1_array = np.array([1,2,3,4,5])
d1_array

array([1, 2, 3, 4, 5])

In [25]:
# 2D
d2_array = np.array([[1,2,3],[4,5,6]])
d2_array

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
d2_array = np.arange(10, 70, 10).reshape(2, 3)
print(d2_array)

[[10 20 30]
 [40 50 60]]

#### 9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [27]:

d4_array = np.random.randint(0, 101, size=(4,4))
print(d4_array)

[[71 13 96 52]
 [83 74 51 21]
 [73 85 84 78]
 [58 46 83 53]]

#### 10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [28]:
import pandas as pd

d2_array = np.arange(10, 100, 10).reshape(3, 3)
print(d2_array)

df = pd.DataFrame(d2_array,  columns= ['A', 'B', 'C'])
df

[[10 20 30]
 [40 50 60]
 [70 80 90]]

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90

### Section C: Exploring Pandas

#### 11. Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [29]:
import numpy as np
import pandas as pd


data = {
    "Name": ["Rahul", "Anita", "Kiran", "Sneha", "Arjun",
             "Meena", "Vikram", "Divya", "Ravi", "Priya"],
    "Age": [25, 30, 28, 22, 35, 27, 31, 22, 29, 26],
    "City": ["Delhi", "Mumbai", "Chennai", "Hyderabad", "Bangaluru",
             "Amaravati", "Kolkata", "Mysuru", "Tirupati", "Vizag"],
    "Salary": [50000, 60000, 55000, 40000, 75000,
               np.nan, 68000, 45000, 58000, 49000]
}
df = pd.DataFrame(data)
df

     Name  Age       City   Salary
0   Rahul   25      Delhi  50000.0
1   Anita   30     Mumbai  60000.0
2   Kiran   28    Chennai  55000.0
3   Sneha   22  Hyderabad  40000.0
4   Arjun   35  Bangaluru  75000.0
5   Meena   27  Amaravati      NaN
6  Vikram   31    Kolkata  68000.0
7   Divya   22     Mysuru  45000.0
8    Ravi   29   Tirupati  58000.0
9   Priya   26      Vizag  49000.0

In [30]:
# using info

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     str
 1   Age     10 non-null     int64
 2   City    10 non-null     str
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), str(2)
memory usage: 452.0 bytes

In [31]:
# using describe

df.describe()

             Age        Salary
count  10.000000      9.000000
mean   27.500000  55555.555556
std     4.034573  11103.052633
min    22.000000  40000.000000
25%    25.250000  49000.000000
50%    27.500000  55000.000000
75%    29.750000  60000.000000
max    35.000000  75000.000000

In [32]:
# finding null values

df.isna().sum()

Name      0
Age       0
City      0
Salary    1
dtype: int64

In [33]:
# select name and city

df[['Name','City']]

     Name       City
0   Rahul      Delhi
1   Anita     Mumbai
2   Kiran    Chennai
3   Sneha  Hyderabad
4   Arjun  Bangaluru
5   Meena  Amaravati
6  Vikram    Kolkata
7   Divya     Mysuru
8    Ravi   Tirupati
9   Priya      Vizag

In [34]:
# droping city

df.drop('City', axis=1, inplace=True)
df

     Name  Age   Salary
0   Rahul   25  50000.0
1   Anita   30  60000.0
2   Kiran   28  55000.0
3   Sneha   22  40000.0
4   Arjun   35  75000.0
5   Meena   27      NaN
6  Vikram   31  68000.0
7   Divya   22  45000.0
8    Ravi   29  58000.0
9   Priya   26  49000.0

In [35]:
# filling mean with null values

df['Salary'] = df['Salary']. fillna(df['Salary'].mean())
df

     Name  Age        Salary
0   Rahul   25  50000.000000
1   Anita   30  60000.000000
2   Kiran   28  55000.000000
3   Sneha   22  40000.000000
4   Arjun   35  75000.000000
5   Meena   27  55555.555556
6  Vikram   31  68000.000000
7   Divya   22  45000.000000
8    Ravi   29  58000.000000
9   Priya   26  49000.000000

In [36]:
# removing duplicate rows

df.drop_duplicates(subset=["Age"], inplace=True)
df.reset_index(drop=True, inplace=True)
df

     Name  Age        Salary
0   Rahul   25  50000.000000
1   Anita   30  60000.000000
2   Kiran   28  55000.000000
3   Sneha   22  40000.000000
4   Arjun   35  75000.000000
5   Meena   27  55555.555556
6  Vikram   31  68000.000000
7    Ravi   29  58000.000000
8   Priya   26  49000.000000