# Python Assignment 4 :Basic Statistics -2

### Permanent File Storage using Google Drive
Run the cell below to connect your Google Drive. Once connected, upload `Patient_Data.csv` into a folder in your Google Drive (for example, a folder named `Colab Notebooks`), and update your file path.

In [9]:
import numpy as np
import pandas as pd

In [10]:
# loading data
patient = pd.read_csv("Patient_Data.csv")

In [11]:
# info of dataset
patient.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      str
 2   Department      6 non-null      str
 3   Doctor          6 non-null      str
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      str
dtypes: float64(1), int64(2), str(4)
memory usage: 468.0 bytes

In [12]:
#finding nulls
patient.isna().sum()

PatientID         0
Name              0
Department        0
Doctor            0
BillAmount        2
ReceptionistID    0
CheckInTime       0
dtype: int64

In [13]:
patient.head(10)

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [14]:
# statistics
patient.describe()

        PatientID   BillAmount  ReceptionistID
count    6.000000     4.000000        6.000000
mean   102.666667  5925.000000        1.666667
std      1.632993  1192.686044        0.816497
min    101.000000  5000.000000        1.000000
25%    101.250000  5000.000000        1.000000
50%    102.500000  5600.000000        1.500000
75%    103.750000  6525.000000        2.000000
max    105.000000  7500.000000        3.000000

In [15]:
# droping unwanted columns
patient.drop(['ReceptionistID',	'CheckInTime'] , axis=1,inplace=True)

In [16]:
# grouping the data by dept
patient.groupby(['Department' , 'BillAmount']).sum()

                        PatientID        Name              Doctor
Department  BillAmount
Cardiology  5000.0            202  AliceAlice  Dr. SmithDr. Smith
            6200.0            104       David           Dr. Smith
Orthopedics 7500.0            103     Charlie             Dr. Lee

In [17]:
# dropping the duplicates
patient = patient.drop_duplicates(subset=['PatientID'])
patient

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

In [18]:
# filling the null values with mean
patient['BillAmount'] = patient['BillAmount'].fillna(patient['BillAmount'].mean())

In [19]:
patient

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

In [20]:
# loding billing dataset
billing = pd.read_csv('Patient_Data.csv')
billing

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [21]:
#concatenate
#pd.concat([patient, billing[['InsuranceCovered',	'FinalAmount']]] , axis=1)

In [22]:
# merging the two data set on basis of Patient_ID
final_result = pd.merge(patient, billing, on='PatientID')
final_result

,PatientID,Name_x,Department_x,Doctor_x,BillAmount_x,Name_y,Department_y,Doctor_y,BillAmount_y,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.000000,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,101,Alice,Cardiology,Dr. Smith,5000.000000,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
2,102,Bob,Neurology,Dr. John,6233.333333,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
3,103,Charlie,Orthopedics,Dr. Lee,7500.000000,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
4,104,David,Cardiology,Dr. Smith,6200.000000,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
5,105,Eva,Dermatology,Dr. Rose,6233.333333,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [23]:

# final grouping the dept
patient.groupby(['Department', 'BillAmount']).sum()

                         PatientID     Name     Doctor
Department  BillAmount
Cardiology  5000.000000        101    Alice  Dr. Smith
            6200.000000        104    David  Dr. Smith
Dermatology 6233.333333        105      Eva   Dr. Rose
Neurology   6233.333333        102      Bob   Dr. John
Orthopedics 7500.000000        103  Charlie    Dr. Lee